package com.Exception;

import java.util.LinkedList;
import java.util.List;

public class ExceptionHandling {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		try {
			int a = 5;
			int b =1;
			int c = a/b;
					System.out.println(c);
					
			String[] word = new String[3];
			word[0] = "ram";
			word[1] = "gopal";
			word[2]= "regan";
				System.out.println(word[1]);	
			
				List l = new LinkedList();
				l.add("donald");
				l.add(123);
				System.out.println(l.get(1));
				
				String s = "python";
				char charAt = s.charAt(0);
				System.out.println(charAt);
				
				
				int parseInt = Integer.parseInt("20.5");
				System.out.println(parseInt);
				
				try {
					String q = "null";
					
					int no = q.lastIndexOf('v');
					System.out.println(no);
					
				}
				
		catch(NullPointerException e) {
			String message = e.getMessage();
			System.out.println(message);
		}
		
		}
		catch(ArithmeticException e) {
			String message = e.getMessage();
		System.out.println(message);
		
		}
		catch(ArrayIndexOutOfBoundsException e) {
			String message = e.getMessage();
			System.out.println(message);
		}
		
		catch(IndexOutOfBoundsException e) {
			String message = e.getMessage();
			System.out.println(message);
		}
		catch(NumberFormatException e) {
			String message = e.getMessage();
			System.out.println(message);
		
		}	
				
		
	}
}
		
